version: '3'
services:
  php:
    build: .docker/php
    volumes:
      - ./app:/app
      - ./.docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - php

  node:
    build:
      context: ./
      dockerfile: .docker/node/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./front:/app
